#!/bin/bash
curl -sLk --cacert /etc/kubernetes/ssl/kube-ca.pem --cert /etc/kubernetes/ssl/kube-service-account-token.pem --key /etc/kubernetes/ssl/kube-service-account-token-key.pem https://127.0.0.1:1020/stats
