#!/bin/bash
NODE="$(kubectl -n kube-system get endpoints kube-controller-manager -o jsonpath='{.metadata.annotations.control-plane\.alpha\.kubernetes\.io/leader}' | jq . 2>/dev/null | grep 'holderIdentity' | awk '{print $2}' | tr -d ",\"" | awk -F '_' '{print $1}')"
echo "kube-controller-manager is the leader on node $NODE"
